### PR TITLE
Feature/02  learning layout

### PR DESCRIPTION
**Pull request by eklemen**

### CODE REVIEW

**Comment by eklemen** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/36

**Comment by eklemen** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues

**Comment by jrutishauser** [comment]
:+1:

**Comment by jaredstevick** [comment]
:+1:  Nice work dude!

**Pull request merged**
